# =============================================
# COMPLETE DATABASE
# =============================================

departments = [
    {"dept_id": 1, "dept_name": "Engineering",        "head": "Rajesh Kumar",  "location": "Block A"},
    {"dept_id": 2, "dept_name": "Data Science",        "head": "Priya Sharma",  "location": "Block B"},
    {"dept_id": 3, "dept_name": "Product Management",  "head": "Amit Patel",    "location": "Block C"},
    {"dept_id": 4, "dept_name": "Marketing",           "head": "Sneha Singh",   "location": "Block D"},
    {"dept_id": 5, "dept_name": "Human Resources",     "head": "Vijay Mehta",   "location": "Block E"},
    {"dept_id": 6, "dept_name": "Design",              "head": "Arjun Reddy",   "location": "Block F"},
    {"dept_id": 7, "dept_name": "DevOps",              "head": "Sunil Joshi",   "location": "Block G"},
]

skills = [
    {"skill_id": 1,  "skill_name": "React.js",          "category": "Frontend"},
    {"skill_id": 2,  "skill_name": "Node.js",            "category": "Backend"},
    {"skill_id": 3,  "skill_name": "JavaScript",         "category": "Programming"},
    {"skill_id": 4,  "skill_name": "MongoDB",            "category": "Database"},
    {"skill_id": 5,  "skill_name": "REST APIs",          "category": "Backend"},
    {"skill_id": 6,  "skill_name": "Python",             "category": "Programming"},
    {"skill_id": 7,  "skill_name": "Machine Learning",   "category": "AI/ML"},
    {"skill_id": 8,  "skill_name": "TensorFlow",         "category": "AI/ML"},
    {"skill_id": 9,  "skill_name": "Deep Learning",      "category": "AI/ML"},
    {"skill_id": 10, "skill_name": "NLP",                "category": "AI/ML"},
    {"skill_id": 11, "skill_name": "Product Strategy",   "category": "Management"},
    {"skill_id": 12, "skill_name": "Agile/Scrum",        "category": "Management"},
    {"skill_id": 13, "skill_name": "Roadmapping",        "category": "Management"},
    {"skill_id": 14, "skill_name": "Stakeholder Mgmt",   "category": "Management"},
    {"skill_id": 15, "skill_name": "Figma",              "category": "Design"},
    {"skill_id": 16, "skill_name": "Adobe XD",           "category": "Design"},
    {"skill_id": 17, "skill_name": "UI Design",          "category": "Design"},
    {"skill_id": 18, "skill_name": "Prototyping",        "category": "Design"},
    {"skill_id": 19, "skill_name": "Docker",             "category": "DevOps"},
    {"skill_id": 20, "skill_name": "Kubernetes",         "category": "DevOps"},
    {"skill_id": 21, "skill_name": "AWS",                "category": "Cloud"},
    {"skill_id": 22, "skill_name": "CI/CD",              "category": "DevOps"},
    {"skill_id": 23, "skill_name": "SQL",                "category": "Database"},
    {"skill_id": 24, "skill_name": "Power BI",           "category": "Analytics"},
    {"skill_id": 25, "skill_name": "Tableau",            "category": "Analytics"},
    {"skill_id": 26, "skill_name": "SEO",                "category": "Marketing"},
    {"skill_id": 27, "skill_name": "Google Ads",         "category": "Marketing"},
    {"skill_id": 28, "skill_name": "Social Media",       "category": "Marketing"},
    {"skill_id": 29, "skill_name": "Content Strategy",   "category": "Marketing"},
    {"skill_id": 30, "skill_name": "Recruitment",        "category": "HR"},
    {"skill_id": 31, "skill_name": "Performance Mgmt",   "category": "HR"},
    {"skill_id": 32, "skill_name": "Employee Relations", "category": "HR"},
    {"skill_id": 33, "skill_name": "HR Analytics",       "category": "HR"},
]

jobs = [
    {
        "job_id": 1, "title": "Senior Full Stack Developer",
        "dept_id": 1, "department": "Engineering",
        "experience_required": 5, "education": "B.Tech/B.E",
        "job_type": "Full-Time", "location": "Bangalore",
        "salary_min": 1200000, "salary_max": 1800000,
        "openings": 3, "posted_date": "2024-01-01",
        "deadline": "2024-03-28", "status": "Open",
        "description": "Looking for a skilled Full Stack Developer with React and Node.js expertise.",
        "required_skills": [1, 2, 3, 4, 5],
    },
    {
        "job_id": 2, "title": "Machine Learning Engineer",
        "dept_id": 2, "department": "Data Science",
        "experience_required": 3, "education": "B.Tech/M.Tech",
        "job_type": "Full-Time", "location": "Hyderabad",
        "salary_min": 1000000, "salary_max": 1600000,
        "openings": 2, "posted_date": "2024-01-05",
        "deadline": "2024-03-25", "status": "Open",
        "description": "Looking for ML Engineer to build AI-powered products.",
        "required_skills": [6, 7, 8, 9, 10],
    },
    {
        "job_id": 3, "title": "Product Manager",
        "dept_id": 3, "department": "Product Management",
        "experience_required": 4, "education": "MBA/B.Tech",
        "job_type": "Full-Time", "location": "Mumbai",
        "salary_min": 1500000, "salary_max": 2500000,
        "openings": 1, "posted_date": "2024-01-08",
        "deadline": "2024-03-20", "status": "Open",
        "description": "Experienced Product Manager to lead cross-functional teams.",
        "required_skills": [11, 12, 13, 14],
    },
    {
        "job_id": 4, "title": "UI/UX Designer",
        "dept_id": 6, "department": "Design",
        "experience_required": 2, "education": "B.Des/B.Tech",
        "job_type": "Full-Time", "location": "Pune",
        "salary_min": 600000, "salary_max": 1200000,
        "openings": 2, "posted_date": "2024-01-10",
        "deadline": "2024-03-22", "status": "Open",
        "description": "Creative UI/UX Designer for our product team.",
        "required_skills": [15, 16, 17, 18],
    },
    {
        "job_id": 5, "title": "DevOps Engineer",
        "dept_id": 7, "department": "DevOps",
        "experience_required": 3, "education": "B.Tech",
        "job_type": "Full-Time", "location": "Chennai",
        "salary_min": 900000, "salary_max": 1500000,
        "openings": 2, "posted_date": "2024-01-12",
        "deadline": "2024-03-28", "status": "Open",
        "description": "DevOps Engineer with CI/CD and cloud platform expertise.",
        "required_skills": [19, 20, 21, 22],
    },
    {
        "job_id": 6, "title": "Data Analyst",
        "dept_id": 2, "department": "Data Science",
        "experience_required": 2, "education": "B.Tech/B.Sc",
        "job_type": "Full-Time", "location": "Delhi",
        "salary_min": 700000, "salary_max": 1200000,
        "openings": 3, "posted_date": "2024-01-15",
        "deadline": "2024-04-01", "status": "Open",
        "description": "Data Analyst to work with business intelligence tools.",
        "required_skills": [6, 23, 24, 25],
    },
]

candidates = [
    {
        "candidate_id": 1, "name": "Rahul Sharma",
        "email": "rahul@email.com", "phone": "9801111111",
        "location": "Bangalore", "experience": 6,
        "education": "B.Tech Computer Science", "college": "IIT Delhi",
        "cgpa": 8.5, "skills": [1, 2, 3, 4, 5],
        "certifications": ["AWS Certified", "Google Cloud"],
        "applied_date": "2024-01-15", "photo": "RS",
    },
    {
        "candidate_id": 2, "name": "Priya Patel",
        "email": "priya@email.com", "phone": "9802222222",
        "location": "Hyderabad", "experience": 4,
        "education": "M.Tech Data Science", "college": "IIT Bombay",
        "cgpa": 9.1, "skills": [6, 7, 8, 9, 10],
        "certifications": ["TensorFlow Developer", "Deep Learning Specialization"],
        "applied_date": "2024-01-16", "photo": "PP",
    },
    {
        "candidate_id": 3, "name": "Amit Kumar",
        "email": "amit@email.com", "phone": "9803333333",
        "location": "Mumbai", "experience": 5,
        "education": "MBA Product Management", "college": "IIM Ahmedabad",
        "cgpa": 8.8, "skills": [11, 12, 13, 14],
        "certifications": ["PMP Certified", "Scrum Master"],
        "applied_date": "2024-01-17", "photo": "AK",
    },
    {
        "candidate_id": 4, "name": "Sneha Singh",
        "email": "sneha@email.com", "phone": "9804444444",
        "location": "Pune", "experience": 3,
        "education": "B.Des Visual Communication", "college": "NID Ahmedabad",
        "cgpa": 8.2, "skills": [15, 16, 17, 18],
        "certifications": ["Google UX Design", "Figma Professional"],
        "applied_date": "2024-01-18", "photo": "SS",
    },
    {
        "candidate_id": 5, "name": "Vijay Mehta",
        "email": "vijay@email.com", "phone": "9805555555",
        "location": "Chennai", "experience": 4,
        "education": "B.Tech Information Technology", "college": "NIT Trichy",
        "cgpa": 8.0, "skills": [19, 20, 21, 22],
        "certifications": ["AWS DevOps", "Kubernetes Administrator"],
        "applied_date": "2024-01-19", "photo": "VM",
    },
    {
        "candidate_id": 6, "name": "Kavita Nair",
        "email": "kavita@email.com", "phone": "9806666666",
        "location": "Delhi", "experience": 3,
        "education": "B.Tech Computer Science", "college": "Delhi University",
        "cgpa": 7.8, "skills": [6, 23, 24, 25],
        "certifications": ["Data Analyst Professional", "Power BI Certified"],
        "applied_date": "2024-01-20", "photo": "KN",
    },
    {
        "candidate_id": 7, "name": "Arjun Reddy",
        "email": "arjun@email.com", "phone": "9807777777",
        "location": "Bangalore", "experience": 5,
        "education": "MBA Marketing", "college": "XLRI Jamshedpur",
        "cgpa": 8.6, "skills": [26, 27, 28, 29],
        "certifications": ["Google Digital Marketing", "HubSpot Marketing"],
        "applied_date": "2024-01-21", "photo": "AR",
    },
    {
        "candidate_id": 8, "name": "Rohit Verma",
        "email": "rohit@email.com", "phone": "9808888888",
        "location": "Bangalore", "experience": 3,
        "education": "B.Tech Computer Science", "college": "VIT Vellore",
        "cgpa": 7.5, "skills": [1, 2, 3],
        "certifications": ["React Developer"],
        "applied_date": "2024-01-22", "photo": "RV",
    },
    {
        "candidate_id": 9, "name": "Anjali Gupta",
        "email": "anjali@email.com", "phone": "9809999999",
        "location": "Hyderabad", "experience": 2,
        "education": "M.Sc Data Science", "college": "BITS Pilani",
        "cgpa": 8.9, "skills": [6, 7, 8, 23],
        "certifications": ["Python for Data Science", "ML A-Z"],
        "applied_date": "2024-01-23", "photo": "AG",
    },
    {
        "candidate_id": 10, "name": "Suresh Kumar",
        "email": "suresh@email.com", "phone": "9800000000",
        "location": "Chennai", "experience": 7,
        "education": "B.Tech IT", "college": "Anna University",
        "cgpa": 8.1, "skills": [1, 2, 3, 4, 5, 19, 21],
        "certifications": ["Full Stack Developer", "AWS Solutions Architect"],
        "applied_date": "2024-01-24", "photo": "SK",
    },
]

applications = [
    {"app_id": 1,  "candidate_id": 1, "job_id": 1, "applied_date": "2024-01-15", "status": "Screened"},
    {"app_id": 2,  "candidate_id": 8, "job_id": 1, "applied_date": "2024-01-22", "status": "Screened"},
    {"app_id": 3,  "candidate_id": 10,"job_id": 1, "applied_date": "2024-01-24", "status": "Screened"},
    {"app_id": 4,  "candidate_id": 2, "job_id": 2, "applied_date": "2024-01-16", "status": "Screened"},
    {"app_id": 5,  "candidate_id": 9, "job_id": 2, "applied_date": "2024-01-23", "status": "Screened"},
    {"app_id": 6,  "candidate_id": 3, "job_id": 3, "applied_date": "2024-01-17", "status": "Screened"},
    {"app_id": 7,  "candidate_id": 4, "job_id": 4, "applied_date": "2024-01-18", "status": "Screened"},
    {"app_id": 8,  "candidate_id": 5, "job_id": 5, "applied_date": "2024-01-19", "status": "Screened"},
    {"app_id": 9,  "candidate_id": 6, "job_id": 6, "applied_date": "2024-01-20", "status": "Screened"},
    {"app_id": 10, "candidate_id": 7, "job_id": 6, "applied_date": "2024-01-21", "status": "Screened"},
]

interviews = [
    {
        "interview_id": 1, "candidate_id": 1, "job_id": 1,
        "round": "Technical Round 1", "date": "2024-02-01",
        "time": "10:00 AM", "mode": "Video Call",
        "interviewer": "Rajesh Kumar", "status": "Completed",
        "rating": 5, "feedback": "Excellent technical skills!",
    },
    {
        "interview_id": 2, "candidate_id": 2, "job_id": 2,
        "round": "Technical Round 1", "date": "2024-02-02",
        "time": "02:00 PM", "mode": "Video Call",
        "interviewer": "Priya Sharma", "status": "Completed",
        "rating": 5, "feedback": "Outstanding ML knowledge.",
    },
    {
        "interview_id": 3, "candidate_id": 3, "job_id": 3,
        "round": "HR Round", "date": "2024-02-03",
        "time": "03:00 PM", "mode": "In Person",
        "interviewer": "Vijay Mehta", "status": "Scheduled",
        "rating": None, "feedback": None,
    },
    {
        "interview_id": 4, "candidate_id": 4, "job_id": 4,
        "round": "Portfolio Review", "date": "2024-02-04",
        "time": "11:00 AM", "mode": "In Person",
        "interviewer": "Arjun Reddy", "status": "Scheduled",
        "rating": None, "feedback": None,
    },
    {
        "interview_id": 5, "candidate_id": 5, "job_id": 5,
        "round": "Technical Round 1", "date": "2024-02-05",
        "time": "10:00 AM", "mode": "Video Call",
        "interviewer": "Sunil Joshi", "status": "Scheduled",
        "rating": None, "feedback": None,
    },
]

hiring = [
    {
        "hiring_id": 1, "candidate_id": 1, "job_id": 1,
        "decision": "Selected", "offer_salary": 1600000,
        "decision_date": "2024-02-10", "joining_date": "2024-03-01",
        "decision_by": "Rajesh Kumar",
    },
    {
        "hiring_id": 2, "candidate_id": 2, "job_id": 2,
        "decision": "Selected", "offer_salary": 1400000,
        "decision_date": "2024-02-08", "joining_date": "2024-03-01",
        "decision_by": "Priya Sharma",
    },
    {
        "hiring_id": 3, "candidate_id": 8, "job_id": 1,
        "decision": "Rejected", "offer_salary": None,
        "decision_date": "2024-02-06", "joining_date": None,
        "decision_by": "Rajesh Kumar",
    },
]